[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
qietr_escrow = "DBLjgT9mCjTF3q7zqDCnUrMtHEnBarNwqmk7XojB4FNz"

[programs.devnet]
qietr_escrow = "DBLjgT9mCjTF3q7zqDCnUrMtHEnBarNwqmk7XojB4FNz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
