[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
qietr_msg = "6ZAeJCLRrNyMCLYgH5uUdRNbA5usAun94vPtaTM5Xdez"

[programs.devnet]
qietr_msg = "6ZAeJCLRrNyMCLYgH5uUdRNbA5usAun94vPtaTM5Xdez"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
