[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
qietr_msg = "2uA7fwAVXbmPNkYsjf5F1zQzxvmQvjNFLCHwSasYqWaL"

[programs.devnet]
qietr_msg = "2uA7fwAVXbmPNkYsjf5F1zQzxvmQvjNFLCHwSasYqWaL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
