// =============================================================================
// vk-to-rust.js
//
// Convert a snarkjs verification_key.json (Groth16, BN254) into a Rust
// const compatible with the groth16-solana crate's `Groth16Verifyingkey`
// struct.
//
// Encoding:
//   - G1 elements:  64 bytes = x (32 BE) || y (32 BE)
//   - G2 elements: 128 bytes = x1 (32 BE) || x0 (32 BE) || y1 (32 BE) || y0 (32 BE)
//   - IC: array of G1 elements, length = nPublic + 1
//
// Usage:
//   node scripts/vk-to-rust.js keys/qietr_payment_dev_vk.json > out.rs
// =============================================================================

const fs = require("fs");
const path = require("path");

function toBE32(dec) {
  let n = BigInt(dec);
  const hex = n.toString(16).padStart(64, "0");
  const out = new Uint8Array(32);
  for (let i = 0; i < 32; i++) {
    out[i] = parseInt(hex.substr(i * 2, 2), 16);
  }
  return out;
}

function fmt(buf) {
  return Array.from(buf)
    .map((b) => "0x" + b.toString(16).padStart(2, "0"))
    .join(", ");
}

function g1(triple) {
  // [x, y, "1"] -> 64 bytes
  const x = toBE32(triple[0]);
  const y = toBE32(triple[1]);
  return Buffer.concat([Buffer.from(x), Buffer.from(y)]);
}

function g2(triple) {
  // [[x0, x1], [y0, y1], ["1", "0"]] -> 128 bytes (Solana syscall order:
  // x1 || x0 || y1 || y0).
  const x0 = toBE32(triple[0][0]);
  const x1 = toBE32(triple[0][1]);
  const y0 = toBE32(triple[1][0]);
  const y1 = toBE32(triple[1][1]);
  return Buffer.concat([
    Buffer.from(x1),
    Buffer.from(x0),
    Buffer.from(y1),
    Buffer.from(y0),
  ]);
}

const vkPath = process.argv[2];
if (!vkPath) {
  console.error("usage: node vk-to-rust.js <vk.json>");
  process.exit(1);
}
const vk = JSON.parse(fs.readFileSync(vkPath, "utf8"));

if (vk.protocol !== "groth16" || vk.curve !== "bn128") {
  console.error("error: expected groth16 / bn128, got", vk.protocol, vk.curve);
  process.exit(1);
}

const nPublic = Number(vk.nPublic);
const alpha = g1(vk.vk_alpha_1);
const beta = g2(vk.vk_beta_2);
const gamma = g2(vk.vk_gamma_2);
const delta = g2(vk.vk_delta_2);
const ic = vk.IC.map(g1);

if (ic.length !== nPublic + 1) {
  console.error(
    "error: IC length",
    ic.length,
    "does not match nPublic + 1 =",
    nPublic + 1,
  );
  process.exit(1);
}

const out = [];
out.push(
  "// Generated by qietr-circuits/scripts/vk-to-rust.js from " +
    path.basename(vkPath),
);
out.push("// DEV KEY. Do not deploy. Regenerate from the production ceremony output.");
out.push("");
out.push("use groth16_solana::groth16::Groth16Verifyingkey;");
out.push("");
out.push("pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {");
out.push(`    nr_pubinputs: ${nPublic},`);
out.push(`    vk_alpha_g1: [${fmt(alpha)}],`);
out.push(`    vk_beta_g2: [${fmt(beta)}],`);
out.push(`    vk_gamme_g2: [${fmt(gamma)}],`);
out.push(`    vk_delta_g2: [${fmt(delta)}],`);
out.push("    vk_ic: &[");
for (const e of ic) {
  out.push(`        [${fmt(e)}],`);
}
out.push("    ],");
out.push("};");

console.log(out.join("\n"));
