// =============================================================================
// tests/helpers.ts — shared fixtures for the qietr-pool mocha suite.
//
// All tests share:
//   * one local validator (started by `anchor test`),
//   * one program instance loaded via Anchor IDL,
//   * a mint we create + control so we can faucet USDC freely,
//   * one shared admin keypair (the singleton pool config can only be
//     initialized once per validator; isolation is per-`denomId` instead).
//
// Proofs are produced via @qietr/sdk's prover against the dev VK baked
// into the on-chain `verifier::VERIFYINGKEY` const.
// =============================================================================

import * as anchor from "@coral-xyz/anchor";
import { AnchorProvider, BN, Program } from "@coral-xyz/anchor";
import {
  createAssociatedTokenAccount,
  createMint,
  getAssociatedTokenAddress,
  getAccount,
  mintTo,
  TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import {
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
  SystemProgram,
} from "@solana/web3.js";
import path from "node:path";
import {
  buildDepositIx,
  buildWithdrawIx,
  buildWitness,
  commitmentHash,
  fieldDecToBE32,
  findDenominationPda,
  findMerkleTreePda,
  findNullifierPda,
  findPoolConfigPda,
  findVaultPda,
  nullifierHash,
  PoseidonMerkleTree,
  proveGroth16,
  pubkeyToFieldString,
  randomFieldDec,
} from "@qietr/sdk";

// Path resolution is anchored to the current working directory rather than
// `__dirname`. The suite imports the ESM-only `@qietr/sdk`, which forces mocha
// to load these tests via the ESM loader (a CJS `require` of the SDK throws
// ERR_REQUIRE_ESM and mocha falls back to `import()`), and in ESM scope
// `__dirname` is undefined. We also can't use `import.meta.url` because
// tsconfig pins `module: commonjs` (TS1343). `process.cwd()` is the only
// resolver that works in both CJS and ESM — and both `anchor test` and the
// `npm test` script run from the qietr-pool directory, so it's deterministic.
const REPO_ROOT = path.resolve(process.cwd(), "..");
export const CIRCUITS_DIR = path.resolve(
  REPO_ROOT,
  "qietr-circuits",
  "build",
);
export const WASM_PATH = path.join(
  CIRCUITS_DIR,
  "qietr_payment_js",
  "qietr_payment.wasm",
);
export const ZKEY_PATH = path.resolve(
  REPO_ROOT,
  "qietr-circuits",
  "keys",
  "qietr_payment_dev.zkey",
);

export const MERKLE_DEPTH = 20;
export const ROOT_HISTORY_LEN = 30;
export const PAY_TIER_MICRO = 10_000_000n; // 10 USDC tier used in tests

export interface Fixture {
  provider: AnchorProvider;
  program: Program<any>;
  admin: Keypair;
  mint: PublicKey;
  configPda: PublicKey;
}

export async function loadProgram(): Promise<Program<any>> {
  // The workspace IDL is generated by `anchor build`. If you see
  // "Cannot find IDL" errors here, you haven't built yet.
  return anchor.workspace.QietrPool as Program<any>;
}

export async function fundAirdrop(
  provider: AnchorProvider,
  to: PublicKey,
  amount: number,
): Promise<void> {
  const sig = await provider.connection.requestAirdrop(
    to,
    amount * LAMPORTS_PER_SOL,
  );
  const bh = await provider.connection.getLatestBlockhash();
  await provider.connection.confirmTransaction(
    { signature: sig, ...bh },
    "confirmed",
  );
}

// The pool config is a global singleton (`seeds = [b"config"]`), so
// `initialize_pool` can succeed exactly once per validator. `anchor test` runs
// the whole suite against one validator, so every test shares a single config,
// admin, and mint. We init lazily on the first call and hand back the cached
// fixture thereafter; per-test isolation comes from a unique `denomId` (the
// denom/tree/vault PDAs are keyed by it) — see `nextDenomId`.
let sharedFixture: Fixture | null = null;

export async function setupBaseFixture(
  provider: AnchorProvider,
  program: Program<any>,
): Promise<Fixture> {
  if (sharedFixture) return sharedFixture;

  const admin = Keypair.generate();
  await fundAirdrop(provider, admin.publicKey, 50);

  // Create a test mint we control (6 decimals like USDC).
  const mint = await createMint(
    provider.connection,
    admin,
    admin.publicKey,
    null,
    6,
  );

  const [configPda] = findPoolConfigPda(program.programId);

  await program.methods
    .initializePool(50) // 50 bps fee
    .accounts({
      config: configPda,
      admin: admin.publicKey,
      systemProgram: SystemProgram.programId,
    })
    .signers([admin])
    .rpc();

  sharedFixture = { provider, program, admin, mint, configPda };
  return sharedFixture;
}

// Monotonic denomination-id allocator. Each test claims a fresh id so its
// denom/tree/vault PDAs don't collide with another test's on the shared
// validator. `denom_id` is a u8 with no on-chain allow-list.
let denomCounter = 1;
export function nextDenomId(): number {
  return denomCounter++;
}

export async function initTier(
  fixture: Fixture,
  denomId: number,
  amountMicro: bigint,
): Promise<{ denomination: PublicKey; tree: PublicKey; vault: PublicKey }> {
  const [denomination] = findDenominationPda(
    denomId,
    fixture.program.programId,
  );
  const [tree] = findMerkleTreePda(denomId, fixture.program.programId);
  const [vault] = findVaultPda(denomId, fixture.program.programId);

  await fixture.program.methods
    .initializeDenomination(denomId, new BN(amountMicro.toString()))
    .accounts({
      config: fixture.configPda,
      denomination,
      tree,
      vault,
      mint: fixture.mint,
      admin: fixture.admin.publicKey,
      tokenProgram: TOKEN_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
      rent: anchor.web3.SYSVAR_RENT_PUBKEY,
    })
    .signers([fixture.admin])
    .rpc();

  return { denomination, tree, vault };
}

export interface DepositorContext {
  user: Keypair;
  ata: PublicKey;
}

export async function createFundedDepositor(
  fixture: Fixture,
  initialMicro: bigint,
): Promise<DepositorContext> {
  const user = Keypair.generate();
  await fundAirdrop(fixture.provider, user.publicKey, 2);
  const ata = await createAssociatedTokenAccount(
    fixture.provider.connection,
    user,
    fixture.mint,
    user.publicKey,
  );
  await mintTo(
    fixture.provider.connection,
    fixture.admin,
    fixture.mint,
    ata,
    fixture.admin,
    Number(initialMicro),
  );
  return { user, ata };
}

export async function depositOnce(
  fixture: Fixture,
  ctx: DepositorContext,
  denomId: number,
  amountMicro: bigint,
  offChainTree: PoseidonMerkleTree,
): Promise<{
  secret: string;
  nullifier: string;
  commitmentDec: string;
  leafIndex: number;
}> {
  const secret = randomFieldDec();
  const nullifier = randomFieldDec();
  const commitmentDec = await commitmentHash(secret, nullifier, amountMicro);
  const commitmentBe = fieldDecToBE32(commitmentDec);

  const [config] = findPoolConfigPda(fixture.program.programId);
  const [denomination] = findDenominationPda(denomId, fixture.program.programId);
  const [tree] = findMerkleTreePda(denomId, fixture.program.programId);
  const [vault] = findVaultPda(denomId, fixture.program.programId);

  const ix = buildDepositIx(
    denomId,
    commitmentBe,
    {
      config,
      denomination,
      tree,
      vault,
      depositorAta: ctx.ata,
      depositor: ctx.user.publicKey,
    },
    fixture.program.programId,
  );

  const tx = new anchor.web3.Transaction().add(ix);
  await anchor.web3.sendAndConfirmTransaction(
    fixture.provider.connection,
    tx,
    [ctx.user],
  );

  const newSize = offChainTree.insert(BigInt(commitmentDec));
  return {
    secret,
    nullifier,
    commitmentDec,
    leafIndex: newSize - 1,
  };
}

export interface WithdrawRunOptions {
  denomId: number;
  commitment: {
    secret: string;
    nullifier: string;
    amountMicro: bigint;
    leafIndex: number;
  };
  recipient: PublicKey; // ATA owner
  paymentMicro: bigint;
  feePayer: Keypair;
  /** Override the offChain tree if you want a stale root (negative test). */
  treeOverride?: PoseidonMerkleTree;
  /** Override the recipient ATA fed into the ix (retarget negative test). */
  recipientAtaOverride?: PublicKey;
  /** Override the nullifier hash arg (mismatch negative test). */
  nullifierHashArgOverride?: Uint8Array;
}

export async function runWithdraw(
  fixture: Fixture,
  offChainTree: PoseidonMerkleTree,
  opts: WithdrawRunOptions,
): Promise<string> {
  const treeToUse = opts.treeOverride ?? offChainTree;
  const path = treeToUse.proof(opts.commitment.leafIndex);

  const recipientFieldDec = pubkeyToFieldString(opts.recipient);

  const witness = await buildWitness(
    {
      secret: opts.commitment.secret,
      nullifier: opts.commitment.nullifier,
      amount: Number(opts.commitment.amountMicro),
      denomId: opts.denomId,
    },
    {
      pathElements: path.pathElements.map((x) => x.toString()),
      pathIndices: path.pathIndices,
      root: path.root.toString(),
    },
    recipientFieldDec,
    opts.paymentMicro,
  );
  const groth = await proveGroth16(witness, WASM_PATH, ZKEY_PATH);

  const nullHashDec = await nullifierHash(opts.commitment.nullifier);
  const nullHashBe = fieldDecToBE32(nullHashDec);

  const [config] = findPoolConfigPda(fixture.program.programId);
  const [denomination] = findDenominationPda(
    opts.denomId,
    fixture.program.programId,
  );
  const [tree] = findMerkleTreePda(opts.denomId, fixture.program.programId);
  const [vault] = findVaultPda(opts.denomId, fixture.program.programId);
  const [nullifierAcct] = findNullifierPda(
    opts.denomId,
    nullHashBe,
    fixture.program.programId,
  );

  const recipientAta =
    opts.recipientAtaOverride ??
    (await getAssociatedTokenAddress(fixture.mint, opts.recipient));

  const ix = buildWithdrawIx(
    opts.denomId,
    opts.nullifierHashArgOverride ?? nullHashBe,
    groth.proofBytes,
    groth.publicSignals,
    {
      config,
      denomination,
      tree,
      vault,
      nullifier: nullifierAcct,
      recipientAta,
      feePayer: opts.feePayer.publicKey,
    },
    fixture.program.programId,
  );

  const tx = new anchor.web3.Transaction().add(ix);
  return anchor.web3.sendAndConfirmTransaction(
    fixture.provider.connection,
    tx,
    [opts.feePayer],
  );
}

export async function ataBalance(
  connection: anchor.web3.Connection,
  ata: PublicKey,
): Promise<bigint> {
  const acct = await getAccount(connection, ata);
  return acct.amount;
}
